---
kind: Namespace
apiVersion: v1
metadata:
  name: federation-manager
  labels:
    name: federation-manager
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: keycloak-config
  namespace: federation-manager
data:
  realm-import.json: |
    {
      "realm": "federation",
      "enabled": true,
      "clientScopes" : [
        {
          "id" : "439d9c71-8a8a-469c-9280-058016000cc2",
          "name" : "fed-mgmt",
          "protocol": "openid-connect",
          "description" : "fed-mgmt"
        }
      ],
      "clients": [
        {
          "clientId": "originating-op-1",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "dd7vNwFqjNpYwaghlEwMbw10g0klWDHb",
          "redirectUris": ["http://localhost:8080/*"],
          "publicClient": false,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": true,
          "defaultClientScopes": ["fed-mgmt"],
          "webOrigins": ["*"]
        }
      ]
    }
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: keycloak
  namespace: federation-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.1.4
          ports:
            - containerPort: 8080
          args: [ "start-dev", "--import-realm" ]
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: admin
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: admin
            - name: KC_IMPORT
              value: /opt/keycloak/data/import/realm-import.json
          volumeMounts:
            - name: realm-import
              mountPath: /opt/keycloak/data/import/
      volumes:
        - name: realm-import
          configMap:
            name: keycloak-config
---
kind: Service
apiVersion: v1
metadata:
  name: keycloak
  namespace: federation-manager
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: keycloak
